using Tmds.Utils;

namespace Tmds.Ssh.Tests;

internal class Program
{
    public static int Main(string[] args)
    {
        // Check if this is an ExecFunction command
        if (ExecFunction.IsExecFunctionCommand(args))
        {
            return ExecFunction.Program.Main(args);
        }

        // Otherwise, delegate to xUnit's generated entry point
        return AutoGenerated.XunitAutoGeneratedEntryPoint.Main(args);
    }
}
